/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    courses: Course;
    placement_tests: PlacementTest;
    placement_attempts: PlacementAttempt;
    media: Media;
    pages: Page;
    users: User;
    admins: Admin;
    coupons: Coupon;
    orders: Order;
    leads: Lead;
    tests: Test;
    classes: Class;
    dashboard_hoc_vu: DashboardHocVu;
    feedback: Feedback;
    vocabulary: Vocabulary;
    branches: Branch;
    rooms: Room;
    band_score: BandScore;
    words: Word;
    'vocab-progress': VocabProgress;
    'personal-vocab': PersonalVocab;
    periodic_tests: PeriodicTest;
    booking_schedule: BookingSchedule;
    periodic_test_attempts: PeriodicTestAttempt;
    care: Care;
    test_backups: TestBackup;
    attendanceRecords: AttendanceRecord;
    role_permissions: RolePermission;
    'homework-assignments': HomeworkAssignment;
    emailTemplates: EmailTemplate;
    timekeeping: Timekeeping;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    courses: CoursesSelect<false> | CoursesSelect<true>;
    placement_tests: PlacementTestsSelect<false> | PlacementTestsSelect<true>;
    placement_attempts: PlacementAttemptsSelect<false> | PlacementAttemptsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    tests: TestsSelect<false> | TestsSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    dashboard_hoc_vu: DashboardHocVuSelect<false> | DashboardHocVuSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    vocabulary: VocabularySelect<false> | VocabularySelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    band_score: BandScoreSelect<false> | BandScoreSelect<true>;
    words: WordsSelect<false> | WordsSelect<true>;
    'vocab-progress': VocabProgressSelect<false> | VocabProgressSelect<true>;
    'personal-vocab': PersonalVocabSelect<false> | PersonalVocabSelect<true>;
    periodic_tests: PeriodicTestsSelect<false> | PeriodicTestsSelect<true>;
    booking_schedule: BookingScheduleSelect<false> | BookingScheduleSelect<true>;
    periodic_test_attempts: PeriodicTestAttemptsSelect<false> | PeriodicTestAttemptsSelect<true>;
    care: CareSelect<false> | CareSelect<true>;
    test_backups: TestBackupsSelect<false> | TestBackupsSelect<true>;
    attendanceRecords: AttendanceRecordsSelect<false> | AttendanceRecordsSelect<true>;
    role_permissions: RolePermissionsSelect<false> | RolePermissionsSelect<true>;
    'homework-assignments': HomeworkAssignmentsSelect<false> | HomeworkAssignmentsSelect<true>;
    emailTemplates: EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    timekeeping: TimekeepingSelect<false> | TimekeepingSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'side-bar': SideBar;
    'violation-rules': ViolationRule;
  };
  globalsSelect: {
    'side-bar': SideBarSelect<false> | SideBarSelect<true>;
    'violation-rules': ViolationRulesSelect<false> | ViolationRulesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  courseName: string;
  tuition?: number | null;
  total_hours?: number | null;
  skills?: ('reading' | 'writing' | 'speaking' | 'listening' | 'grammar' | 'vocabulary')[] | null;
  type?: ('online' | 'offline') | null;
  thumbnail?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement_tests".
 */
export interface PlacementTest {
  id: string;
  title: string;
  description?: string | null;
  type: 'mini' | 'full' | 'sat';
  tests: (string | Test)[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tests".
 */
export interface Test {
  id: string;
  name: string;
  type: 'reading' | 'writing' | 'speaking' | 'listening' | 'grammar' | 'vocab';
  isVisibleOnLMS?: boolean | null;
  isFullTest?: boolean | null;
  test_type: ('homework' | 'extra_homework' | 'mini_test' | 'mid_term' | 'final_term' | 'bank' | 'entrance_test')[];
  authors?: (string | Admin)[] | null;
  'listening-audio'?: (string | null) | Media;
  listening: {
    listeningType: 'Section 1' | 'Section 2' | 'Section 3' | 'Section 4';
    title: string;
    description:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    transcript?: string | null;
    vocabs?: (string | Word)[] | null;
    sections?:
      | {
          description:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          content: (
            | {
                options?:
                  | {
                      value: string;
                      label: string;
                      id?: string | null;
                    }[]
                  | null;
                questions: {
                  questionNumber: number;
                  correctAnswer: string;
                  question: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'matchingInfo';
              }
            | {
                diagramImage: string | Media;
                options?:
                  | {
                      value: string;
                      label: string;
                      id?: string | null;
                    }[]
                  | null;
                questions: {
                  questionNumber: number;
                  correctAnswer: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'planMapDiagramLabeling';
              }
            | {
                questions: {
                  questionNumber: number;
                  question: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  answer: {
                    answer: string;
                    correctAnswer: boolean;
                    id?: string | null;
                  }[];
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'chooseTitle';
              }
            | {
                diagramImage: string | Media;
                questions: {
                  questionNumber: number;
                  correctAnswer: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'digramCompletion';
              }
            | {
                questions:
                  | {
                      [k: string]: unknown;
                    }
                  | unknown[]
                  | string
                  | number
                  | boolean
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'flowChartCompletion';
              }
            | {
                matchingLabel?: string | null;
                options?:
                  | {
                      value: string;
                      label: string;
                      id?: string | null;
                    }[]
                  | null;
                questions: {
                  questionNumber: number;
                  correctAnswer: string;
                  question: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'matchingHeading';
              }
            | {
                options?:
                  | {
                      option: string;
                      id?: string | null;
                    }[]
                  | null;
                questions: {
                  questionNumber: number;
                  correctAnswer: string;
                  question: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'matchingName';
              }
            | {
                options: string;
                questions: {
                  questionNumber: number;
                  question: string;
                  correctAnswer: string;
                  answerLocation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'matchingParagraphInfo';
              }
            | {
                options?:
                  | {
                      value: string;
                      label?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                questions: {
                  questionNumber: number;
                  question: string;
                  correctAnswer: string;
                  answerLocation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'matchingSentenceEnding';
              }
            | {
                questions: {
                  question: string;
                  answer: {
                    answer: string;
                    correctAnswer: boolean;
                    id?: string | null;
                  }[];
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'multipleChoice';
              }
            | {
                questions:
                  | {
                      [k: string]: unknown;
                    }
                  | unknown[]
                  | string
                  | number
                  | boolean
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'sentenceCompletion';
              }
            | {
                questions: {
                  questionNumber: number;
                  question?: string | null;
                  correctAnswer: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'shortAnswer';
              }
            | {
                questions:
                  | {
                      [k: string]: unknown;
                    }
                  | unknown[]
                  | string
                  | number
                  | boolean
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'summaryCompletion';
              }
            | {
                questions:
                  | {
                      [k: string]: unknown;
                    }
                  | unknown[]
                  | string
                  | number
                  | boolean
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'tableCompletion';
              }
            | {
                questions: {
                  questionNumber: number;
                  correctAnswer: 'true' | 'false' | 'not_given';
                  question: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'trueFalseNotGiven';
              }
            | {
                questions: {
                  questionNumber: number;
                  correctAnswer: 'yes' | 'no' | 'not_given';
                  question: string;
                  answerLocation?: string | null;
                  explanation?: string | null;
                  questionTitle?: string | null;
                  locationParagraph?: string | null;
                  locateTime?: string | null;
                  id?: string | null;
                }[];
                id?: string | null;
                blockName?: string | null;
                blockType: 'yesNoNotGiven';
              }
          )[];
          id?: string | null;
        }[]
      | null;
    brainstorm?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  writing: {
    writingType: '1' | '2';
    description:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    image?: (string | null) | Media;
    content:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    brainstorm?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sample?: string | null;
    id?: string | null;
  }[];
  reading?:
    | {
        passageType: '1' | '2' | '3';
        title: string;
        image?: (string | null) | Media;
        description:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        passage:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        vocabs?: (string | Word)[] | null;
        sections?:
          | {
              description:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              content: (
                | {
                    questions: {
                      questionNumber: number;
                      question: string;
                      answerLocation?: string | null;
                      explanation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      answer: {
                        answer: string;
                        correctAnswer: boolean;
                        id?: string | null;
                      }[];
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'chooseTitle';
                  }
                | {
                    diagramImage: string | Media;
                    questions: {
                      questionNumber: number;
                      correctAnswer: string;
                      answerLocation?: string | null;
                      explanation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'digramCompletion';
                  }
                | {
                    questions:
                      | {
                          [k: string]: unknown;
                        }
                      | unknown[]
                      | string
                      | number
                      | boolean
                      | null;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'flowChartCompletion';
                  }
                | {
                    matchingLabel?: string | null;
                    options?:
                      | {
                          value: string;
                          label: string;
                          id?: string | null;
                        }[]
                      | null;
                    questions: {
                      questionNumber: number;
                      correctAnswer: string;
                      question: string;
                      answerLocation?: string | null;
                      explanation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'matchingHeading';
                  }
                | {
                    options?:
                      | {
                          option: string;
                          id?: string | null;
                        }[]
                      | null;
                    questions: {
                      questionNumber: number;
                      correctAnswer: string;
                      question: string;
                      answerLocation?: string | null;
                      explanation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'matchingName';
                  }
                | {
                    options: string;
                    questions: {
                      questionNumber: number;
                      question: string;
                      correctAnswer: string;
                      answerLocation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'matchingParagraphInfo';
                  }
                | {
                    options?:
                      | {
                          value: string;
                          label?: string | null;
                          id?: string | null;
                        }[]
                      | null;
                    questions: {
                      questionNumber: number;
                      question: string;
                      correctAnswer: string;
                      answerLocation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'matchingSentenceEnding';
                  }
                | {
                    questions: {
                      question: string;
                      answer: {
                        answer: string;
                        correctAnswer: boolean;
                        id?: string | null;
                      }[];
                      answerLocation?: string | null;
                      explanation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'multipleChoice';
                  }
                | {
                    questions:
                      | {
                          [k: string]: unknown;
                        }
                      | unknown[]
                      | string
                      | number
                      | boolean
                      | null;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'sentenceCompletion';
                  }
                | {
                    questions: {
                      questionNumber: number;
                      question?: string | null;
                      correctAnswer: string;
                      answerLocation?: string | null;
                      explanation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'shortAnswer';
                  }
                | {
                    questions:
                      | {
                          [k: string]: unknown;
                        }
                      | unknown[]
                      | string
                      | number
                      | boolean
                      | null;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'summaryCompletion';
                  }
                | {
                    questions:
                      | {
                          [k: string]: unknown;
                        }
                      | unknown[]
                      | string
                      | number
                      | boolean
                      | null;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'tableCompletion';
                  }
                | {
                    questions: {
                      questionNumber: number;
                      correctAnswer: 'true' | 'false' | 'not_given';
                      question: string;
                      answerLocation?: string | null;
                      explanation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'trueFalseNotGiven';
                  }
                | {
                    questions: {
                      questionNumber: number;
                      correctAnswer: 'yes' | 'no' | 'not_given';
                      question: string;
                      answerLocation?: string | null;
                      explanation?: string | null;
                      questionTitle?: string | null;
                      locationParagraph?: string | null;
                      locateTime?: string | null;
                      id?: string | null;
                    }[];
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'yesNoNotGiven';
                  }
              )[];
              id?: string | null;
            }[]
          | null;
        brainstorm?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  speaking?:
    | {
        sectionType: '1' | '2' | '3';
        Topics: {
          topic: string;
          questions: {
            question: string;
            brainstorm?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            sampleBelow7?: string | null;
            sampleAbove7?: string | null;
            vocabs?: (string | Word)[] | null;
            id?: string | null;
          }[];
          you_should_say?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  grammar?: {
    description:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sections: {
      questions: {
        question: string;
        answer: {
          answer: string;
          correctAnswer: boolean;
          id?: string | null;
        }[];
        answerLocation?: string | null;
        explanation?: string | null;
        questionTitle?: string | null;
        locationParagraph?: string | null;
        locateTime?: string | null;
        id?: string | null;
      }[];
      id?: string | null;
      blockName?: string | null;
      blockType: 'multipleChoice';
    }[];
    brainstorm?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  vocab?: {
    description:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sections: {
      questions: {
        question: string;
        answer: {
          answer: string;
          correctAnswer: boolean;
          id?: string | null;
        }[];
        answerLocation?: string | null;
        explanation?: string | null;
        questionTitle?: string | null;
        locationParagraph?: string | null;
        locateTime?: string | null;
        id?: string | null;
      }[];
      id?: string | null;
      blockName?: string | null;
      blockType: 'multipleChoice';
    }[];
    brainstorm?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  department: 'ceo' | 'hoc_vu' | 'hoc_thuat' | 'sale' | 'marketing' | 'hr' | 'ke_toan' | '25';
  role?:
    | (
        | 'admin'
        | 'hoc_vu_manager'
        | 'hoc_vu_executive'
        | 'academic_manager'
        | 'academic_executive'
        | 'teacher_part_time'
        | 'teacher_full_time'
        | 'wow_manager'
        | 'wow_executive'
        | 'sale_manager'
        | 'sale_executive'
        | 'marketing_manager'
        | 'marketing_executive'
        | 'designer'
        | 'seo'
        | 'digital_marketing'
        | 'hr_manager'
        | 'hr_generalist'
        | 'ke_toan'
      )
    | null;
  fullName: string;
  phone: string;
  birthday?: string | null;
  working_date?: string | null;
  address?: string | null;
  avatar?: (string | null) | Media;
  /**
   * Dùng để gửi cho học viên khi học WOW trực tuyến
   */
  meetingLink?: string | null;
  availability?:
    | {
        /**
         * Chọn ngày rảnh của WOW để học sinh có thể book. Ví dụ bắt đầu vào ngày 01/01/2025 9:00 và kết thúc vào ngày 01/01/2025 17:00. Có thể chọn nhiều khung giờ khác nhau cùng ngày nếu như ngày đó WOW rảnh vào nhiều khung giờ
         */
        start_date: string;
        end_date: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "words".
 */
export interface Word {
  id: string;
  word: string;
  pronunciation?: string | null;
  type?: ('adj' | 'n' | 'v' | 'adv' | 'conj') | null;
  'meaning-vn'?: string | null;
  /**
   * Giới hạn 95 kí tự.
   */
  'meaning-en'?: string | null;
  example?: string | null;
  level?: string | null;
  synonyms?: (string | Word)[] | null;
  antonyms?: (string | Word)[] | null;
  'sentence-use'?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement_attempts".
 */
export interface PlacementAttempt {
  id: string;
  user: string | Lead;
  test: string | PlacementTest;
  type: string;
  status: 'pending' | 'completed' | 'in_progress';
  score?: (string | null) | BandScore;
  startedAt?: string | null;
  completedAt?: string | null;
  duration?: string | null;
  statusDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  answerSheet?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  displayTitle?: string | null;
  title?: string | null;
  fullName?: string | null;
  phone?: string | null;
  email?: string | null;
  gender?: ('male' | 'female') | null;
  'parent name'?: string | null;
  'parent phone'?: string | null;
  'parent email'?: string | null;
  date_of_birth?: string | null;
  link_facebook?: string | null;
  address?: string | null;
  type?: ('student' | 'college_student' | 'office_worker' | 'parent' | 'other') | null;
  target?: number | null;
  wow_quota?: number | null;
  purpose?: string | null;
  branch?: (string | null) | Branch;
  source:
    | 'facebook'
    | 'google'
    | 'hotline'
    | 'walking'
    | 'referral'
    | 'seeding'
    | 'school_tour'
    | 'sponsorship'
    | 're_enroll'
    | 'from_website'
    | 'other';
  saleInCharge?: (string | null) | Admin;
  status?:
    | (
        | 'waiting_for_call'
        | 'test_booked'
        | 'test_not_booked'
        | 'potential'
        | 'not_potential'
        | 'paid_case'
        | 'failed_case'
        | 'consider'
      )
    | null;
  courses?: string | null;
  coupon?: (string | Coupon)[] | null;
  notes?:
    | {
        channel_interaction?: ('zalo' | 'phone' | 'fanpage' | 'hotline' | 'direct_message' | 'online') | null;
        appointment_date?: string | null;
        status?:
          | (
              | 'waiting_for_call'
              | 'test_booked'
              | 'test_not_booked'
              | 'potential'
              | 'not_potential'
              | 'paid_case'
              | 'failed_case'
              | 'consider'
            )
          | null;
        message?: string | null;
        createdAt?: string | null;
        createdBy?: (string | null) | Admin;
        id?: string | null;
      }[]
    | null;
  chats?:
    | {
        createdBy?: (string | null) | Admin;
        message?: string | null;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: string;
  name: string;
  address: string;
  phone: string;
  rooms: (string | Room)[];
  status?: ('active' | 'unactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: string;
  name: string;
  capacity?: number | null;
  status?: ('active' | 'unactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  name: string;
  discount: number;
  type: 'money' | 'percent';
  startDate: string;
  endDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "band_score".
 */
export interface BandScore {
  id: string;
  score: string;
  skillLevel?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  avatar?: (string | null) | Media;
  role: 'user';
  lead?: (string | null) | Lead;
  violationStatus?: ('none' | 'warning_1' | 'warning_2' | 'terminated') | null;
  displayTitle?: string | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  customer?: (string | null) | User;
  courses?: (string | Course)[] | null;
  coupon?: (string | Coupon)[] | null;
  status?: ('full' | 'installment') | null;
  note?: string | null;
  saleInCharge?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: string;
  name: string;
  type_class?: ('group' | 'one_to_one') | null;
  course?: (string | null) | Course;
  startDate: string;
  /**
   * Học vào những ngày nào trong tuần. Ví dụ: Thứ 2, Thứ 4, Thứ 6. Được chọn nhiều
   */
  days_of_week?: ('1' | '2' | '3' | '4' | '5' | '6' | '0')[] | null;
  session_time?: string | null;
  total_hours?: number | null;
  time_per_session?: number | null;
  students?: (string | User)[] | null;
  status_class?: ('opening' | 'active' | 'closed') | null;
  link_zoom?: string | null;
  branch?: (string | null) | Branch;
  room?: (string | null) | Room;
  teachers?:
    | {
        /**
         * Chọn giáo viên phụ trách cho lớp. Được chọn nhiều. Chỉ hiển thị giáo viên full-time và part-time
         */
        teacher?: (string | null) | Admin;
        skill?: ('reading' | 'writing' | 'speaking' | 'listening' | 'grammar' | 'vocabulary')[] | null;
        /**
         * Dạy vào những ngày nào trong tuần. Ví dụ: Thứ 2, Thứ 4, Thứ 6. Được chọn nhiều
         */
        days_of_week?: ('1' | '2' | '3' | '4' | '5' | '6' | '0')[] | null;
        session_time?: string | null;
        duration?: number | null;
        id?: string | null;
      }[]
    | null;
  sessions?:
    | {
        date: string;
        teacher?: (string | null) | Admin;
        session_time?: string | null;
        duration?: number | null;
        id?: string | null;
      }[]
    | null;
  roadmaps?:
    | {
        skill?: ('reading' | 'writing' | 'speaking' | 'listening' | 'grammar' | 'vocabulary') | null;
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard_hoc_vu".
 */
export interface DashboardHocVu {
  id: string;
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: string;
  title?: string | null;
  class: string | Class;
  feedback_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  student_review_session?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vocabulary".
 */
export interface Vocabulary {
  id: string;
  name: string;
  level?: string | null;
  thumbnail?: (string | null) | Media;
  words: (string | Word)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vocab-progress".
 */
export interface VocabProgress {
  id: string;
  user: string | User;
  word: (string | Word)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personal-vocab".
 */
export interface PersonalVocab {
  id: string;
  user: string | User;
  name: string;
  words: (string | Word)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "periodic_tests".
 */
export interface PeriodicTest {
  id: string;
  title: string;
  description?: string | null;
  type: 'homework' | 'extra_homework' | 'mini_test' | 'mid_term' | 'final_term' | 'bank' | 'entrance_test';
  tests: (string | Test)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking_schedule".
 */
export interface BookingSchedule {
  id: string;
  schedule_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  wow_manager_config?: {
    /**
     * Ví dụ: 1 thì chỉ thấy tuần hiện tại, 2 thì thấy cả tuần sau.
     */
    visibleWeeks?: number | null;
    /**
     * Ví dụ: 1 thì hôm nay thứ 4 không thể đặt các ca của thứ 4. 2 thì không thể đặt thứ 4 và thứ 5.
     */
    leadTimeDays?: number | null;
    /**
     * Số lượng cột (số học sinh tối đa) có thể đăng ký trong cùng một khung giờ.
     */
    maxSlotsPerCell?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "periodic_test_attempts".
 */
export interface PeriodicTestAttempt {
  id: string;
  user: string | User;
  test: string | PeriodicTest;
  type: 'homework' | 'extra_homework' | 'mini_test' | 'mid_term' | 'final_term' | 'bank' | 'entrance_test';
  status: 'pending' | 'completed' | 'in_progress';
  class?: (string | null) | Class;
  session?: number | null;
  score?: (string | null) | BandScore;
  startedAt?: string | null;
  completedAt?: string | null;
  duration?: string | null;
  mode?: ('practice' | 'simulation') | null;
  part?: string | null;
  time?: number | null;
  statusDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  answerSheet?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "care".
 */
export interface Care {
  id: string;
  class_ref?: (string | null) | Class;
  class_status?: ('pending' | 'approve_pending' | 'opening' | 'active' | 'closed') | null;
  care_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test_backups".
 */
export interface TestBackup {
  id: string;
  placementAttempt?: (string | null) | PlacementAttempt;
  answerSheet?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  statusDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  type: 'homework' | 'periodic' | 'placement';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendanceRecords".
 */
export interface AttendanceRecord {
  id: string;
  class: string | Class;
  AttendanceRecord_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ViolationRecord_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "role_permissions".
 */
export interface RolePermission {
  id: string;
  permissions:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homework-assignments".
 */
export interface HomeworkAssignment {
  id: string;
  class: string | Class;
  teachers: (string | Admin)[];
  type_class?: ('group' | 'one_to_one') | null;
  /**
   * Lưu trữ thông tin giao bài tập (session id -> homework mapping)
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailTemplates".
 */
export interface EmailTemplate {
  id: string;
  title: string;
  subject: string;
  image?: (string | null) | Media;
  /**
   * Hỗ trợ thẻ HTML cơ bản (<br/>, <b>, <i>, <p>). Các biến được hỗ trợ tự động điền: {{studentName}}, {{violationList}}, {{levelText}}
   */
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timekeeping".
 */
export interface Timekeeping {
  id: string;
  dummy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'placement_tests';
        value: string | PlacementTest;
      } | null)
    | ({
        relationTo: 'placement_attempts';
        value: string | PlacementAttempt;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'tests';
        value: string | Test;
      } | null)
    | ({
        relationTo: 'classes';
        value: string | Class;
      } | null)
    | ({
        relationTo: 'dashboard_hoc_vu';
        value: string | DashboardHocVu;
      } | null)
    | ({
        relationTo: 'feedback';
        value: string | Feedback;
      } | null)
    | ({
        relationTo: 'vocabulary';
        value: string | Vocabulary;
      } | null)
    | ({
        relationTo: 'branches';
        value: string | Branch;
      } | null)
    | ({
        relationTo: 'rooms';
        value: string | Room;
      } | null)
    | ({
        relationTo: 'band_score';
        value: string | BandScore;
      } | null)
    | ({
        relationTo: 'words';
        value: string | Word;
      } | null)
    | ({
        relationTo: 'vocab-progress';
        value: string | VocabProgress;
      } | null)
    | ({
        relationTo: 'personal-vocab';
        value: string | PersonalVocab;
      } | null)
    | ({
        relationTo: 'periodic_tests';
        value: string | PeriodicTest;
      } | null)
    | ({
        relationTo: 'booking_schedule';
        value: string | BookingSchedule;
      } | null)
    | ({
        relationTo: 'periodic_test_attempts';
        value: string | PeriodicTestAttempt;
      } | null)
    | ({
        relationTo: 'care';
        value: string | Care;
      } | null)
    | ({
        relationTo: 'test_backups';
        value: string | TestBackup;
      } | null)
    | ({
        relationTo: 'attendanceRecords';
        value: string | AttendanceRecord;
      } | null)
    | ({
        relationTo: 'role_permissions';
        value: string | RolePermission;
      } | null)
    | ({
        relationTo: 'homework-assignments';
        value: string | HomeworkAssignment;
      } | null)
    | ({
        relationTo: 'emailTemplates';
        value: string | EmailTemplate;
      } | null)
    | ({
        relationTo: 'timekeeping';
        value: string | Timekeeping;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admins';
        value: string | Admin;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admins';
        value: string | Admin;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  courseName?: T;
  tuition?: T;
  total_hours?: T;
  skills?: T;
  type?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement_tests_select".
 */
export interface PlacementTestsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  tests?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement_attempts_select".
 */
export interface PlacementAttemptsSelect<T extends boolean = true> {
  user?: T;
  test?: T;
  type?: T;
  status?: T;
  score?: T;
  startedAt?: T;
  completedAt?: T;
  duration?: T;
  statusDetails?: T;
  answerSheet?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  role?: T;
  lead?: T;
  violationStatus?: T;
  displayTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  department?: T;
  role?: T;
  fullName?: T;
  phone?: T;
  birthday?: T;
  working_date?: T;
  address?: T;
  avatar?: T;
  meetingLink?: T;
  availability?:
    | T
    | {
        start_date?: T;
        end_date?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  name?: T;
  discount?: T;
  type?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customer?: T;
  courses?: T;
  coupon?: T;
  status?: T;
  note?: T;
  saleInCharge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  displayTitle?: T;
  title?: T;
  fullName?: T;
  phone?: T;
  email?: T;
  gender?: T;
  'parent name'?: T;
  'parent phone'?: T;
  'parent email'?: T;
  date_of_birth?: T;
  link_facebook?: T;
  address?: T;
  type?: T;
  target?: T;
  wow_quota?: T;
  purpose?: T;
  branch?: T;
  source?: T;
  saleInCharge?: T;
  status?: T;
  courses?: T;
  coupon?: T;
  notes?:
    | T
    | {
        channel_interaction?: T;
        appointment_date?: T;
        status?: T;
        message?: T;
        createdAt?: T;
        createdBy?: T;
        id?: T;
      };
  chats?:
    | T
    | {
        createdBy?: T;
        message?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tests_select".
 */
export interface TestsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  isVisibleOnLMS?: T;
  isFullTest?: T;
  test_type?: T;
  authors?: T;
  'listening-audio'?: T;
  listening?:
    | T
    | {
        listeningType?: T;
        title?: T;
        description?: T;
        transcript?: T;
        vocabs?: T;
        sections?:
          | T
          | {
              description?: T;
              content?:
                | T
                | {
                    matchingInfo?:
                      | T
                      | {
                          options?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    planMapDiagramLabeling?:
                      | T
                      | {
                          diagramImage?: T;
                          options?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    chooseTitle?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                answer?:
                                  | T
                                  | {
                                      answer?: T;
                                      correctAnswer?: T;
                                      id?: T;
                                    };
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    digramCompletion?:
                      | T
                      | {
                          diagramImage?: T;
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    flowChartCompletion?:
                      | T
                      | {
                          questions?: T;
                          id?: T;
                          blockName?: T;
                        };
                    matchingHeading?:
                      | T
                      | {
                          matchingLabel?: T;
                          options?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    matchingName?:
                      | T
                      | {
                          options?:
                            | T
                            | {
                                option?: T;
                                id?: T;
                              };
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    matchingParagraphInfo?:
                      | T
                      | {
                          options?: T;
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                question?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    matchingSentenceEnding?:
                      | T
                      | {
                          options?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                question?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    multipleChoice?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                question?: T;
                                answer?:
                                  | T
                                  | {
                                      answer?: T;
                                      correctAnswer?: T;
                                      id?: T;
                                    };
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    sentenceCompletion?:
                      | T
                      | {
                          questions?: T;
                          id?: T;
                          blockName?: T;
                        };
                    shortAnswer?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                question?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    summaryCompletion?:
                      | T
                      | {
                          questions?: T;
                          id?: T;
                          blockName?: T;
                        };
                    tableCompletion?:
                      | T
                      | {
                          questions?: T;
                          id?: T;
                          blockName?: T;
                        };
                    trueFalseNotGiven?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    yesNoNotGiven?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
            };
        brainstorm?: T;
        id?: T;
      };
  writing?:
    | T
    | {
        writingType?: T;
        description?: T;
        image?: T;
        content?: T;
        brainstorm?: T;
        sample?: T;
        id?: T;
      };
  reading?:
    | T
    | {
        passageType?: T;
        title?: T;
        image?: T;
        description?: T;
        passage?: T;
        vocabs?: T;
        sections?:
          | T
          | {
              description?: T;
              content?:
                | T
                | {
                    chooseTitle?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                answer?:
                                  | T
                                  | {
                                      answer?: T;
                                      correctAnswer?: T;
                                      id?: T;
                                    };
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    digramCompletion?:
                      | T
                      | {
                          diagramImage?: T;
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    flowChartCompletion?:
                      | T
                      | {
                          questions?: T;
                          id?: T;
                          blockName?: T;
                        };
                    matchingHeading?:
                      | T
                      | {
                          matchingLabel?: T;
                          options?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    matchingName?:
                      | T
                      | {
                          options?:
                            | T
                            | {
                                option?: T;
                                id?: T;
                              };
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    matchingParagraphInfo?:
                      | T
                      | {
                          options?: T;
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                question?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    matchingSentenceEnding?:
                      | T
                      | {
                          options?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                question?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    multipleChoice?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                question?: T;
                                answer?:
                                  | T
                                  | {
                                      answer?: T;
                                      correctAnswer?: T;
                                      id?: T;
                                    };
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    sentenceCompletion?:
                      | T
                      | {
                          questions?: T;
                          id?: T;
                          blockName?: T;
                        };
                    shortAnswer?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                question?: T;
                                correctAnswer?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    summaryCompletion?:
                      | T
                      | {
                          questions?: T;
                          id?: T;
                          blockName?: T;
                        };
                    tableCompletion?:
                      | T
                      | {
                          questions?: T;
                          id?: T;
                          blockName?: T;
                        };
                    trueFalseNotGiven?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    yesNoNotGiven?:
                      | T
                      | {
                          questions?:
                            | T
                            | {
                                questionNumber?: T;
                                correctAnswer?: T;
                                question?: T;
                                answerLocation?: T;
                                explanation?: T;
                                questionTitle?: T;
                                locationParagraph?: T;
                                locateTime?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
            };
        brainstorm?: T;
        id?: T;
      };
  speaking?:
    | T
    | {
        sectionType?: T;
        Topics?:
          | T
          | {
              topic?: T;
              questions?:
                | T
                | {
                    question?: T;
                    brainstorm?: T;
                    sampleBelow7?: T;
                    sampleAbove7?: T;
                    vocabs?: T;
                    id?: T;
                  };
              you_should_say?: T;
              id?: T;
            };
        id?: T;
      };
  grammar?:
    | T
    | {
        description?: T;
        sections?:
          | T
          | {
              multipleChoice?:
                | T
                | {
                    questions?:
                      | T
                      | {
                          question?: T;
                          answer?:
                            | T
                            | {
                                answer?: T;
                                correctAnswer?: T;
                                id?: T;
                              };
                          answerLocation?: T;
                          explanation?: T;
                          questionTitle?: T;
                          locationParagraph?: T;
                          locateTime?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        brainstorm?: T;
      };
  vocab?:
    | T
    | {
        description?: T;
        sections?:
          | T
          | {
              multipleChoice?:
                | T
                | {
                    questions?:
                      | T
                      | {
                          question?: T;
                          answer?:
                            | T
                            | {
                                answer?: T;
                                correctAnswer?: T;
                                id?: T;
                              };
                          answerLocation?: T;
                          explanation?: T;
                          questionTitle?: T;
                          locationParagraph?: T;
                          locateTime?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        brainstorm?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  name?: T;
  type_class?: T;
  course?: T;
  startDate?: T;
  days_of_week?: T;
  session_time?: T;
  total_hours?: T;
  time_per_session?: T;
  students?: T;
  status_class?: T;
  link_zoom?: T;
  branch?: T;
  room?: T;
  teachers?:
    | T
    | {
        teacher?: T;
        skill?: T;
        days_of_week?: T;
        session_time?: T;
        duration?: T;
        id?: T;
      };
  sessions?:
    | T
    | {
        date?: T;
        teacher?: T;
        session_time?: T;
        duration?: T;
        id?: T;
      };
  roadmaps?:
    | T
    | {
        skill?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard_hoc_vu_select".
 */
export interface DashboardHocVuSelect<T extends boolean = true> {
  settings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  title?: T;
  class?: T;
  feedback_data?: T;
  student_review_session?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vocabulary_select".
 */
export interface VocabularySelect<T extends boolean = true> {
  name?: T;
  level?: T;
  thumbnail?: T;
  words?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  phone?: T;
  rooms?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  capacity?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "band_score_select".
 */
export interface BandScoreSelect<T extends boolean = true> {
  score?: T;
  skillLevel?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "words_select".
 */
export interface WordsSelect<T extends boolean = true> {
  word?: T;
  pronunciation?: T;
  type?: T;
  'meaning-vn'?: T;
  'meaning-en'?: T;
  example?: T;
  level?: T;
  synonyms?: T;
  antonyms?: T;
  'sentence-use'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vocab-progress_select".
 */
export interface VocabProgressSelect<T extends boolean = true> {
  user?: T;
  word?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personal-vocab_select".
 */
export interface PersonalVocabSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  words?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "periodic_tests_select".
 */
export interface PeriodicTestsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  tests?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking_schedule_select".
 */
export interface BookingScheduleSelect<T extends boolean = true> {
  schedule_data?: T;
  wow_manager_config?:
    | T
    | {
        visibleWeeks?: T;
        leadTimeDays?: T;
        maxSlotsPerCell?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "periodic_test_attempts_select".
 */
export interface PeriodicTestAttemptsSelect<T extends boolean = true> {
  user?: T;
  test?: T;
  type?: T;
  status?: T;
  class?: T;
  session?: T;
  score?: T;
  startedAt?: T;
  completedAt?: T;
  duration?: T;
  mode?: T;
  part?: T;
  time?: T;
  statusDetails?: T;
  answerSheet?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "care_select".
 */
export interface CareSelect<T extends boolean = true> {
  class_ref?: T;
  class_status?: T;
  care_data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test_backups_select".
 */
export interface TestBackupsSelect<T extends boolean = true> {
  placementAttempt?: T;
  answerSheet?: T;
  statusDetails?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendanceRecords_select".
 */
export interface AttendanceRecordsSelect<T extends boolean = true> {
  class?: T;
  AttendanceRecord_data?: T;
  ViolationRecord_data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "role_permissions_select".
 */
export interface RolePermissionsSelect<T extends boolean = true> {
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homework-assignments_select".
 */
export interface HomeworkAssignmentsSelect<T extends boolean = true> {
  class?: T;
  teachers?: T;
  type_class?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailTemplates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  title?: T;
  subject?: T;
  image?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timekeeping_select".
 */
export interface TimekeepingSelect<T extends boolean = true> {
  dummy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "side-bar".
 */
export interface SideBar {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "violation-rules".
 */
export interface ViolationRule {
  id: string;
  no_camera_threshold: number;
  no_camera_warning_2: number;
  no_camera_terminated: number;
  absent_without_permission_threshold: number;
  absent_without_permission_warning_2: number;
  absent_without_permission_terminated: number;
  absent_with_permission_threshold: number;
  absent_with_permission_warning_2: number;
  absent_with_permission_terminated: number;
  late_homework_threshold: number;
  late_homework_warning_2: number;
  late_homework_terminated: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "side-bar_select".
 */
export interface SideBarSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "violation-rules_select".
 */
export interface ViolationRulesSelect<T extends boolean = true> {
  no_camera_threshold?: T;
  no_camera_warning_2?: T;
  no_camera_terminated?: T;
  absent_without_permission_threshold?: T;
  absent_without_permission_warning_2?: T;
  absent_without_permission_terminated?: T;
  absent_with_permission_threshold?: T;
  absent_with_permission_warning_2?: T;
  absent_with_permission_terminated?: T;
  late_homework_threshold?: T;
  late_homework_warning_2?: T;
  late_homework_terminated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}