export const COLLECTIONS = [
  "users",
  "admins",
  "leads",
  "classes",
  "attendanceRecords",
  "orders",
  "courses",
  "rooms",
  "branches",
  "feedbacks",
  "coupons",
  "schedule",
  "bookingSchedule",
  "studentCare",
  "care",
  "bandScore",
  "examSessions",
  "testBackups",
  "tests",
  "questionSets",
  "placementTests",
  "placementAttempts",
  "periodicTests",
  "periodicTestAttempts",
  "vocabulary",
  "words",
  "personalVocabulary",
  "vocabularyProgress",
  "media",
  "pages",
  "roles",
  "permissions",
  "site-settings",
];

export const ROLES = [
  { label: "CEO (Admin)", value: "admin" },
  { label: "Học vụ Manager", value: "hoc_vu_manager" },
  { label: "Học vụ Executive", value: "hoc_vu_executive" },
  { label: "Academic Manager", value: "academic_manager" },
  { label: "Teacher Part-Time", value: "teacher_part_time" },
  { label: "Teacher Full-Time", value: "teacher_full_time" },
  { label: "WOW Manager", value: "wow_manager" },
  { label: "WOW Executive", value: "wow_executive" },
  { label: "Sales Manager", value: "sales_manager" },
  { label: "Sales Executive", value: "sales_executive" },
  { label: "Marketing Manager", value: "marketing_manager" },
  { label: "Marketing Executive", value: "marketing_executive" },
  { label: "Designer", value: "designer" },
  { label: "SEO", value: "seo" },
  { label: "Digital Marketing", value: "digital_marketing" },
  { label: "HR Manager", value: "hr_manager" },
  { label: "HR Generalist", value: "hr_generalist" },
  { label: "Accountant", value: "accountant" },
  { label: "Teacher (Legacy)", value: "teacher" },
  { label: "Học vụ (Legacy)", value: "hocvu" },
  { label: "Sales (Legacy)", value: "sale" },
];
