"use client";

import {
  Activity,
  Archive,
  Award,
  Book,
  BookOpen,
  Briefcase,
  CalendarClock,
  ClipboardCheck,
  Compass,
  Crown,
  Database,
  DoorOpen,
  Drama,
  File,
  FileStack,
  FileText,
  FileUpIcon,
  Fingerprint,
  FolderCog,
  FolderOpen,
  GraduationCap,
  HeartHandshake,
  History,
  LayoutDashboard,
  LayoutList,
  Library,
  Mail,
  MapPin,
  Martini,
  MessageSquare,
  Pizza,
  Receipt,
  Rocket,
  ShieldAlert,
  SpellCheck,
  Target,
  UserCheck,
  Clock,
  UserRoundCheckIcon,
  Users,
} from "lucide-react";
import { SidebarIconProvider } from "payload-sidebar-plugin/components";
import React from "react";

const customIcons = {
  rocket: (props: any) => <Rocket {...props} />,
  class: (props: any) => <BookOpen {...props} />,
  users: (props: any) => <Users {...props} />,
  Book: (props: any) => <Book {...props} />,
  MapPin: (props: any) => <MapPin {...props} />,
  martini: (props: any) => <Martini {...props} />,
  pizza: (props: any) => <Pizza {...props} />,
  compass: (props: any) => <Compass {...props} />,
  DoorOpen: (props: any) => <DoorOpen {...props} />,
  drama: (props: any) => <Drama {...props} />,
  Activity: (props: any) => <Activity {...props} />,
  Briefcase: (props: any) => <Briefcase {...props} />,
  dashboard_hoc_vu: (props: any) => <LayoutDashboard {...props} />,
  schedule: (props: any) => <CalendarClock {...props} />,
  attendance: (props: any) => <ClipboardCheck {...props} />,
  fingerprint: Fingerprint,
  ClipboardCheck: (props: any) => <ClipboardCheck {...props} />,
  Receipt: (props: any) => <Receipt {...props} />,
  UserCheck: (props: any) => <UserCheck {...props} />,
  Users: (props: any) => <Users {...props} />,
  HeartHandshake: (props: any) => <HeartHandshake {...props} />,
  image: (props: any) => <FolderCog {...props} />,
  GraduationCap: (props: any) => <GraduationCap {...props} />,
  MessageSquare: (props: any) => <MessageSquare {...props} />,
  ClipboardList: (props: any) => <MessageSquare {...props} />,
  FileQuestion: (props: any) => <MessageSquare {...props} />,
  PenLine: (props: any) => <MessageSquare {...props} />,
  Archive: (props: any) => <Archive {...props} />,
  FileText: (props: any) => <FileText {...props} />,
  Library: (props: any) => <Library {...props} />,
  Crown: (props: any) => <Crown {...props} />,
  Award: (props: any) => <Award {...props} />,
  LayoutList: (props: any) => <LayoutList {...props} />,
  FileStack: (props: any) => <FileStack {...props} />,
  File: (props: any) => <File {...props} />,
  words: (props: any) => <File {...props} />,
  Database: (props: any) => <Database {...props} />,
  History: (props: any) => <History {...props} />,
  FolderOpen: (props: any) => <FolderOpen {...props} />,
  SpellCheck: (props: any) => <SpellCheck {...props} />,
  Target: (props: any) => <Target {...props} />,
  ShieldAlert: (props: any) => <ShieldAlert {...props} />,
  Permission: (props: any) => <UserRoundCheckIcon {...props} />,
  FileUpIcon: (props: any) => <FileUpIcon {...props} />,
  Mail: (props: any) => <Mail {...props} />,
  Timekeeping: (props: any) => <Clock {...props} />,
};

export function SidebarIcons({ children }: { children: React.ReactNode }) {
  return (
    <SidebarIconProvider icons={customIcons}>{children}</SidebarIconProvider>
  );
}
